# Generated by Django 4.1.3 on 2022-11-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Login', models.CharField(default='DefauldLogin', max_length=45)),
                ('Password', models.CharField(default='123', max_length=45)),
                ('Role', models.SmallIntegerField(default=0)),
                ('LastLogin', models.DateTimeField(auto_now=True)),
                ('ImageUsers', models.ImageField(default='No', upload_to='')),
                ('Mail', models.EmailField(default='test@mail.ru', max_length=254, verbose_name=100)),
                ('UserCity', models.CharField(default='Ставрополь', max_length=45)),
            ],
        ),
    ]
