# Generated by Django 4.1.3 on 2022-11-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
