# Generated by Django 4.1.3 on 2022-11-14 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_alter_post_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
