# Generated by Django 4.1.3 on 2022-11-21 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_alter_post_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='Post',
        ),
    ]
